#!/bin/bash

# Install AWS CLI
sudo yum install -y aws-cli

# Configure credentials profile name for 's3_access'
aws configure set aws_access_key_id AKIASCG33VXFQINQ5LLE
aws configure set aws_secret_access_key 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

# Download script from S3 bucket
aws s3 cp s3://deploy-script.sh/script.sh /tmp/script.sh

# Make script executable
chmod +x /tmp/script.sh

# Execute the script
/tmp/script.sh

